# -*- coding: utf-8 -*-
"""Web agents for Avalon game."""
# -*- coding: utf-8 -*-
"""Web agents for Avalon game."""
from typing import Any
from agentscope.agent import AgentBase, UserAgent
from agentscope.message import Msg

from games.avalon.web.game_state_manager import GameStateManager
from games.avalon.web.web_user_input import WebUserInput
from games.avalon.utils import Parser


class WebUserAgent(UserAgent):
    """Web-based UserAgent that syncs observations to frontend and uses WebUserInput."""
    
    def __init__(
        self,
        name: str,
        state_manager: GameStateManager,
    ):
        """Initialize WebUserAgent.
        
        Args:
            name: Agent name
            state_manager: GameStateManager instance
        """
        super().__init__(name=name)
        self.state_manager = state_manager
        self.agent_id = self.id
        
        # Override input method to use WebUserInput
        web_input = WebUserInput(state_manager)
        self.override_instance_input_method(web_input)

    async def reply(
        self,
        msg: Msg | list[Msg] | None = None,
        structured_model: Any = None,
    ) -> Msg:
        """Receive input message(s) and generate a reply message from the user.
        
        Args:
            msg: The message(s) to be replied. If not None, observe them first.
            structured_model: Optional structured model for structured input.
            
        Returns:
            The reply message generated by the user.
        """
        # Observe the incoming message(s) first
        if msg is not None:
            await self.observe(msg)
        
        # Call parent reply to get user input
        return await super().reply(msg=msg, structured_model=structured_model)

    async def observe(self, msg: Msg | list[Msg] | None) -> None:
        """Observe messages and sync to frontend.
        
        Args:
            msg: Message(s) to observe
        """
        # Call parent observe first
        await super().observe(msg)
        
        # Sync to frontend (only in participate mode)
        if self.state_manager.mode == "participate":
            if msg is None:
                return
            
            # Handle both single message and list of messages
            messages = msg if isinstance(msg, list) else [msg]
            
            for m in messages:
                if isinstance(m, Msg):
                    content = Parser.extract_text_from_content(m.content)
                    message_dict = self.state_manager.format_message(
                        sender=m.name,
                        content=content,
                        role=m.role,
                    )
                    await self.state_manager.broadcast_message(message_dict)


class ObserveAgent(AgentBase):
    """Observer agent that syncs all messages to frontend in observe mode."""
    
    def __init__(
        self,
        name: str = "Observer",
        state_manager: GameStateManager | None = None,
    ):
        """Initialize ObserveAgent.
        
        Args:
            name: Agent name
            state_manager: GameStateManager instance
        """
        super().__init__()
        self.name = name
        self.state_manager = state_manager or GameStateManager()
    
    async def observe(self, msg: Msg | list[Msg] | None) -> None:
        """Observe all messages and sync to frontend.
        
        Args:
            msg: Message(s) to observe
        """
        if msg is None:
            return
        
        # Handle both single message and list of messages
        messages = msg if isinstance(msg, list) else [msg]
        
        for m in messages:
            if isinstance(m, Msg):
                content = Parser.extract_text_from_content(m.content)
                message_dict = self.state_manager.format_message(
                    sender=m.name,
                    content=content,
                    role=m.role,
                )
                await self.state_manager.broadcast_message(message_dict)
    
    async def reply(self, content: str) -> Msg:
        """Observer agent doesn't reply, but we implement this for compatibility.
        
        Args:
            content: Content to reply (not used)
            
        Returns:
            Empty message
        """
        return Msg(
            self.name,
            content="",
            role="assistant",
        )

